FROM yukikurosawadev/edk2:noble-dev

RUN cd /mnt && \
  git clone --recursive https://github.com/tianocore/edk2.git edk2 && \
  cd edk2 && \
  git checkout edk2-stable202408 && \
  cd .. && \
  git clone https://github.com/Yuki-Kurosawa/YukiUEFI.git YukiPkg

RUN cat /etc/sudoers | sed -re 's/(%sudo.*)\sALL$/\1 NOPASSWD:ALL/g' > /etc/sudoers.new && \
  rm -rf /etc/sudoers && \
  cp /etc/sudoers.new /etc/sudoers && \
  chmod 0440 /etc/sudoers

ENTRYPOINT ["/usr/libexec/entrypoint"]